### ISSUE TITLE
项目在AS3.6上不能编译

### ISSUE THREAD

**Issue by IronManIsTheMan** [leavesC/ReactiveHttp#11]

**Comment by madreain** [comment]
欢迎使用 https://github.com/madreain/AACHulk，并提出相关问题

**Comment by leavesCZY** [comment]
> _No description provided._

难道你用的是mac？

**Comment by IronManIsTheMan** [comment]
是的兄弟，感谢回复。

**Comment by leavesC** [comment]
> 是的兄弟，感谢回复。



> 是的兄弟，感谢回复。



> 是的兄弟，感谢回复。

那个应该是文件路径分隔符Windows和mac不一样导致的，之前已经修改了，你重新拉代码就可以了

**Comment by leavesCZY** [comment]
> 是的兄弟，感谢回复。

那个应该是文件路径分隔符Windows和mac不一样导致的，之前已经修改了，你重新拉代码就可以了
