### ISSUE TITLE
在其他地方看到了你的文章

### ISSUE THREAD

**Issue by kanshenmekan** [leavesC/ReactiveHttp#12]
看到Repo类和viewMode也用liveData传值，ViewMode持有了LifecycleOwner，是不是不合理，直接用回调传值就行了

**Comment by leavesCZY** [comment]
> 看到Repo类和viewMode也用liveData传值，ViewMode持有了LifecycleOwner，是不是不合理，直接用回调传值就行了

你可以拉下最新代码，目前最新的逻辑就是通过 callback 来进行回调的
