### ISSUE TITLE
java版本请同步更新

### ISSUE THREAD

**Issue by caik123** [leavesC/ReactiveHttp#13]
同步更新java版本呀，2.0 kotlin版本都是一个完整的天气app了，java版本落后了呀

**Comment by leavesCZY** [comment]
> 同步更新java版本呀，2.0 kotlin版本都是一个完整的天气app了，java版本落后了呀

抱歉，java 版本是不会再更新的了，我觉得对于目前的 Android 开发者来说，kotlin + coroutines + jetpack 才是最为主流且迫切的技术栈
