### ISSUE TITLE
可以提供上传及下载的示例吗

### ISSUE THREAD

**Issue by xiayuyu** [leavesC/ReactiveHttp#14]

**Comment by STGing** [comment]
同问一下，因为有的项目中免不了会有一些文件下载上传，比如说头像、用户拍照图片(文件)等等。我看到说明里面说专注于接口，没有上传下载功能，那请教一下，如果在这个库的基础上，增加上传下载的话，思路或者集成什么会好一点。（考虑过三方的文件上传下载的库，但是感觉网络这方面可能会有很多重复的封装什么的）

**Comment by leavesCZY** [comment]
> 同问一下，因为有的项目中免不了会有一些文件下载上传，比如说头像、用户拍照图片(文件)等等。我看到说明里面说专注于接口，没有上传下载功能，那请教一下，如果在这个库的基础上，增加上传下载的话，思路或者集成什么会好一点。（考虑过三方的文件上传下载的库，但是感觉网络这方面可能会有很多重复的封装什么的）

由于我自己的项目中很少用到下载功能，所以没有对这一块进行封装处理，对这一块没怎么了解，没法给你建议，抱歉哈
