### ISSUE TITLE
如何在fragment中使用

### ISSUE THREAD

**Issue by aaaTang** [leavesC/ReactiveHttp#16]
我试着在写了BaseFragment：Fragment(),IUIActionEventObserver
{
override val lContext: Context?
        get() = context

    override val lLifecycleOwner: LifecycleOwner
        get() = this

    override val lifecycleSupportedScope: CoroutineScope
        get() = lifecycleScope
}
这种写法正常用没问题，可是会出现内存泄漏问题，麻烦问一下怎么处理

**Comment by leavesCZY** [comment]
请问内存泄漏指向的是哪里呢？你要详细描述下我才能确定原因呀
