### ISSUE TITLE
多个请求 async 如何处理异常，try catch抓不到 会崩溃

### ISSUE THREAD

**Issue by caixingcun** [leavesC/ReactiveHttp#18]
fun <DataA, DataB> enqueue(apiFunA: suspend Api.() -> IHttpWrapBean<DataA>,
                               apiFunB: suspend Api.() -> IHttpWrapBean<DataB>,
                               showLoading: Boolean = false,
                               callbackFun: (RequestPairCallback<DataA, DataB>.() -> Unit)? = null): Job {
        return launchMain {
            val callback = if (callbackFun == null) null else RequestPairCallback<DataA, DataB>().apply {
                callbackFun.invoke(this)
            }
            try {
                if (showLoading) {
                    showLoading(coroutineContext[Job])
                }
                //  callbackFun()
                callback?.onStart?.invoke()
                val responseList: List<IHttpWrapBean<out Any?>>
                try {
                    responseList = listOf(
                            // requestLogin()
                            async { apiFunA.invoke(getApiService()) },
                            async { apiFunB.invoke(getApiService()) }
                    ).awaitAll()
                    val failed = responseList.find { it.httpIsFailed }
                    if (failed != null) {
                        throw ServerCodeBadException(failed)
                    }
                } catch (throwable: Throwable) {
                    handleException(throwable, callback)
                    return@launchMain
                }
                onGetResponse(callback, responseList)
            } finally {
                try {
                    callback?.onFinally?.invoke()
                } finally {
                    if (showLoading) {
                        dismissLoading()
                    }
                }
            }
        }
    }

**Comment by leavesCZY** [comment]
这里的确存在问题，你可以暂时使用这个修复版本：implementation 'com.github.leavesC:ReactiveHttp:745ddd19b3'
