### ISSUE TITLE
ReactiveFragment 为啥不添加open方便被继承使用

### ISSUE THREAD

**Issue by jpsz01** [leavesC/ReactiveHttp#22]

**Comment by leavesCZY** [comment]
抱歉，这个的确是我的疏忽，当时没有注意到这个问题。但我有个小小的建议，像这类三方框架，如果是非必须继承的话，最好还是自己在项目实现必要的接口就好

**Comment by leavesCZY** [comment]
v1.1.3 已开放 ReactiveFragment，并补充了相关的使用示例
