### ISSUE TITLE
Repo层真的有必要存在吗

### ISSUE THREAD

**Issue by JokeenZhang** [leavesC/ReactiveHttp#4]
每完成一个类型的接口请求，都要实现很多的类，这样来看，Repo是否就没有必要存在？毕竟DataSource就足矣承担任务。当然，如果这个类型的接口较为复杂的话，Repo的存在也是有必要的，比如还存在paging

**Comment by leavesCZY** [comment]
> 每完成一个类型的接口请求，都要实现很多的类，这样来看，Repo是否就没有必要存在？毕竟DataSource就足矣承担任务。当然，如果这个类型的接口较为复杂的话，Repo的存在也是有必要的，比如还存在paging

这个其实我也是有点犹豫，或者可以在需要它存在的时候就再建立吧
