### ISSUE TITLE
楼主请教下。网络这块是没有封装下载大文件吗？

### ISSUE THREAD

**Issue by 1184104588** [leavesC/ReactiveHttp#5]
如题

**Comment by leavesC** [comment]
本Repo的定位其实是介绍如何进行封装，而非一个完整的网络请求框架，大文件下载这个直接用OkHttp就可以完成的

**Comment by leavesCZY** [comment]
> 如题

本Repo的定位其实是介绍如何进行封装，而非一个完整的网络请求框架，大文件下载这个直接用OkHttp就可以完成的
