### ISSUE TITLE
很好的学习框架封装

### ISSUE THREAD

**Issue by a9151357635** [leavesC/ReactiveHttp#8]
很好的学些框架封装，可让我重构项目中采用你的思路，谢谢作者，不合理的地方或者有好的建议一定会跟作者说明

**Comment by leavesCZY** [comment]
> 很好的学些框架封装，可让我重构项目中采用你的思路，谢谢作者，不合理的地方或者有好的建议一定会跟作者说明
抱歉哈，平时比较少关注 issue，也很谢谢你的评价
